In [1]:
%pip install numpy


[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
gusy = np.array([1,2,3,4])

print(type(gusy))

print(gusy)

<class 'numpy.ndarray'>
[1 2 3 4]


Properties associated with numpy arrays

In [6]:
print("Gusy, ndim", gusy.ndim)
print("Gusy, shape", gusy.shape)
print("Gusy, size", gusy.size)
print("Gusy, dtype", gusy.dtype)

Gusy, ndim 1
Gusy, shape (4,)
Gusy, size 4
Gusy, dtype int64


In [18]:
array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [19]:
print('Array_2: ', array_2)

Array_2:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
print("array_2, ndim", array_2.ndim)
print("array_2, shape", array_2.shape)
print("array_2, size", array_2.size)
print("array_2, dtype", array_2.dtype)

array_2, ndim 2
array_2, shape (2, 5)
array_2, size 10
array_2, dtype int64


Reshaping the array

In [22]:
array_3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [23]:
print(array_3)

print(array_3.reshape(5,3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Indexing and slicing numpy arrays (same as lists)

In [24]:
data = np.array([1,2,3])

print(data[1])

print(data[0:2])

print(data[:-1])

2
[1 2]
[1 2]


Methods of Numpy Arrays


In [27]:
np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.linspace(0,10,num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [37]:
#Adding and sorting elements in a numpy array

array_4 = np.array([2,1,5,3,4,7,4,5,2,5,3])

print(np.sort(array_4))

print(array_4)

[1 2 2 3 3 4 4 5 5 5 7]
[2 1 5 3 4 7 4 5 2 5 3]


In [39]:
x = np.array([[1,2,3,4,5],[3,4,5,6,7]])

y = np.array([[7,8,9,10,11],[1,2,3,4,5]])

print(np.concatenate((x,y), axis =0))
print(np.concatenate((x,y), axis =1))

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]]
[[ 1  2  3  4  5  7  8  9 10 11]
 [ 3  4  5  6  7  1  2  3  4  5]]


In [40]:
array_5 = np.arange(2,20,2)

In [42]:
print(array_5)

print(np.sum(array_5))

[ 2  4  6  8 10 12 14 16 18]
90
